version: '3'
networks:
  tau-net:
    driver: bridge
services:
  sqlpad:
    build: ./sqlpad/server
    entrypoint: /docker-entrypoint
    volumes:
      - .:/sqlpad
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - tau-net
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: sqlpad
      POSTGRES_DB: sqlpad
    ports: 
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - tau-net
